source 'https://github.com/gupengling/GPLSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform:ios,’9.0’
use_frameworks!
target 'GPLChangeThemeDemo' do
pod 'AFNetworking'
pod 'GPLChangeTheme/Swift', :path => "../"
end


